version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mern-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: rootPass
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: mern-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mernUser:mernPass@mongo:27017/mern-todo
    depends_on:
      - mongo
    ports:
      - "8000:8001"
  frontend:
    build: ./frontend
    container_name: mern-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo-data: