apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aleksandra0710/mern-todo-backend:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret